adam_b1= 0.8
adam_b2= 0.99
batch_size=12

val_clean_ref = false
validate_only = false

val_interval = 20000
distinct_chkpt_interval = 20000
max_steps = 3500000

num_workers = 4


num_mels=80
fmin=0
fmax=8000

cuda_visible_devices = "0"
train_name = "snake_causal_doubleseg_BVRNN_correct"
resume = true

coder_type = "bvrnn"
var_bit = true
p_bitratechange = 0.3

bvrnn_chkpt = "/media/DATA/shared/stahl/bernoulli-var-speech-codec/variable_BitrateKLMask/checkpoints/200000"
vocoder_chkpt_g = "pretrained_and_finetuned_vocoder_chkpts/bigvgan_causal_tiny_g_2500000"
vocoder_chkpt_do = "pretrained_and_finetuned_vocoder_chkpts/bigvgan_causal_tiny_do_2500000"

h_dim = 1024
z_dim = 64
log_sigma_init = -1.0

fs = 22050
winsize = 1024
hopsize = 256
mel_pad_left=256

train_seq_duration = 4.0
resblock="1"
learning_rate= 0.0001

pre_sym = false
upsample_rates= [8,8,2,2]
upsample_kernel_sizes= [16,16,4,4]
upsample_initial_channel= 128
resblock_kernel_sizes= [3,7,11]
resblock_dilation_sizes= [[1,3,5], [1,3,5], [1,3,5]]
layers_sym = [false, false, false, false]
layers_antialias = [false, false, false, false]
antialias_post= false
post_sym = false

activation= "snakebeta"
snake_logscale= true

resolutions=[[1024, 120, 600], [2048, 240, 1200], [512, 50, 240]]
mpd_reshapes=[2, 3, 5, 7, 11]
use_spectral_norm= false
discriminator_channel_mult= 1

msl_fmin=0
msl_fmax=11025
msl_num_mels=80
